#!/bin/bash
FILES=./"$1"/*
dirEntered="$1"
len=${#dirEntered}
len=$(($len + 3))
rm all_tokens.txt
for f in $FILES; do
	echo "Tokenizing ${f:len} file..."
	# take action on each file. $f store current file name
	echo -ne "${f:len} " >>all_tokens.txt
	./scanner $f
	echo -ne "" >>tokens.txt
	cat tokens.txt >>all_tokens.txt
	echo "" >>tokens.txt
done
echo "Detecting Plagarism, this may take a few minutes."
./cmos
echo "Done. Results stored in Scores.txt"
